<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Browse\Enums;

class CompatibilityMatchEnum
{
    const C_EXACT = 'EXACT';
    const C_POSSIBLE = 'POSSIBLE';
}